### ISSUE TITLE
定时器的时间间隔

### ISSUE THREAD

**Issue by youlookdelicious** [herobin22/OYCountDownManager#1]
如果把定时器的时间间隔改成0.01s,CPU是不是要爆炸?

**Comment by herobin22** [comment]
0.01s也只是毫秒级, cpu的频率都是Ghz级, 所以0.01s刷新一次也不会导致cpu爆炸, 0.01s刷新一次也没什么意义, 因为用户感受不到, 只感受到手机发热吧....
