### ISSUE TITLE
单独的倒计时怎么应用呢？

### ISSUE THREAD

**Issue by SunYanpeng2017** [herobin22/OYCountDownManager#9]
你好，我列表和详情都需要用到倒计时，这里只写到了列表的倒计时，没写到单独的倒计时应用，请问应该如何应用呢？

**Comment by herobin22** [comment]
请看文档  四.高级使用
增加一个倒计时源, 监听通知, 设置回调即可

**Comment by SunYanpeng2017** [comment]
嗯嗯  列表和详情都有倒计时，[kCountDownManager invalidate];方法是不是只需要在列表控制器的dealloc方法里写就可以，不然吐过详情和列表里都写，从列表点进详情，再从详情返回列表，列表的倒计时就停了
